# Generated by Django 5.2.3 on 2025-07-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_trgm_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_name_trgm',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='event_location_trgm',
        ),
    ]
